#11605 (2.4.3.alpha.p7) Fix typo and exit 1 if build fails.
=== pari-2.4.3.alpha.p7 (Leif Leonhardy, July 16th, 2011) ===
 * #11605: Fix typo in spkg-install and add `exit 1` (again) in case
   the build fails.
 * Quote some more variables and filenames in messages.

Also added GNU patch to the dependencies section and
fixed the years of the previous three Changelog entries... ;-)

diff --git a/build/pkgs/pari/spkg-install b/build/pkgs/pari/spkg-install
--- a/build/pkgs/pari/spkg-install
+++ b/build/pkgs/pari/spkg-install
@@ -17,9 +17,9 @@ TOP=`pwd`
 #######################################################################
 cd src
 for patch in ../patches/*.patch; do
-    patch -p0 <$patch
+    patch -p0 <"$patch"
     if [ $? -ne 0 ]; then
-        echo >&2 "Error applying $patch"
+        echo >&2 "Error applying '$patch'"
         exit 1
     fi
 done
@@ -180,8 +180,9 @@ build()
     fi
 
     $MAKE $PARI_MAKEFLAGS gp
-    if [ $? -ne 0]; then
-        echo >&2 "Error: building PARI/GP failed."
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: Building PARI/GP failed."
+        exit 1
     fi
 }
 
@@ -257,6 +258,6 @@ else
     pari_shlib="libpari.so"
 fi
 if [ ! -f "$SAGE_LOCAL/lib/$pari_shlib" ]; then
-    echo "Error: PARI's shared library $pari_shlib has not been installed!"
+    echo "Error: PARI's shared library '$pari_shlib' has not been installed!"
     exit 1
 fi
