#Remove spkg-check file, as there are no self-tests for this version of patch.

diff --git a/build/pkgs/patch/spkg-install b/build/pkgs/patch/spkg-install
--- a/build/pkgs/patch/spkg-install
+++ b/build/pkgs/patch/spkg-install
@@ -49,3 +49,10 @@ if [ $? -ne 0 ]; then
     echo "Error installing GNU patch"
     exit 1
 fi
+
+# Sanity check that we have the correct version of patch
+# in our PATH.
+if ! patch --version | grep >/dev/null 'patch 2\.5\.9'; then
+    echo "Cannot to find the patch program we just installed"
+    exit 1
+fi
