#11666: Rewrote spkg-check based on MPIR's one.

diff --git a/build/pkgs/mpfr/spkg-check b/build/pkgs/mpfr/spkg-check
--- a/build/pkgs/mpfr/spkg-check
+++ b/build/pkgs/mpfr/spkg-check
@@ -1,7 +1,18 @@
-cd src
-make check
+#!/usr/bin/env bash
 
+if [ -z "$SAGE_LOCAL" ]; then
+    echo "Error: SAGE_LOCAL undefined - exiting..."
+    echo "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
+# unset RM since it messes with libtool
+unset RM
+
+cd src
+
+$MAKE check
 if [ $? -ne 0 ]; then
-  echo "There was a problem during the mpfr tests."
+  echo "Error: the MPFR test suite failed."
   exit 1
 fi
