Trac #11635: use NTL libtool system for building and installing

diff --git a/build/pkgs/ntl/spkg-check b/build/pkgs/ntl/spkg-check
--- a/build/pkgs/ntl/spkg-check
+++ b/build/pkgs/ntl/spkg-check
@@ -1,30 +1,18 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+    echo >&2 "SAGE_LOCAL undefined ... exiting";
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
-
-if [ $UNAME = "Darwin" ]; then
-   echo "Setting SHAREDFLAGS to '-fno-common'"
-   export SHAREDFLAGS="-fno-common"
-fi
-
-CUR=`pwd`
 
 cd src/src
 
-CFLAGS="-O2 -g $CFLAGS"
-CXXFLAGS="-O2 -g $CXXFLAGS"
+echo "Testing NTL."
 
-if [ `uname` = "Darwin" -a "$SAGE64" = "yes" ]; then
-   CFLAGS=" -m64 $CFLAGS"
-   CXXFLAGS=" -m64 $CXXFLAGS"
-fi
+$MAKE check
 
-make check
-if ! [ $? -eq 0 ]; then
-    echo "Failed to run make check target for NTL"
+if [ $? -ne 0 ]; then
+    echo >&2 "Failed to run make check target for NTL"
     exit 1
 fi
