[project @ patch to sage-1.0.1]

diff --git a/src/spkg-install b/src/spkg-install
--- a/src/spkg-install
+++ b/src/spkg-install
@@ -44,3 +44,8 @@ ln -sf $E sage
 
 cd $E
 python setup.py install
+
+if [ $? -ne 0 ]; then
+    echo "ERROR installing SAGE"
+    exit 1
+fi
